### ISSUE TITLE
Update MTBC lineages

### ISSUE THREAD

**Issue by iqbal-lab** [Mykrobe-tools/mykrobe#22] opened 2018-08-31 15:56 UTC
Will mean we have sublineage too.
See
https://github.com/philipwfowler/snpit/blob/master/snpit/core.py
and 
https://github.com/philipwfowler/snpit/blob/master/lib/library.csv

**Comment by martinghunt** [comment] 2020-10-16 08:15
Closing this. Is duplicate of #94

**Closed by martinghunt** 2020-10-16 08:15 UTC
Labels: enhancement
